import { StyleSheet } from "react-native";
import { COLORS } from "../../constants";

export const buyerDashboardStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.light.background },
  header: {
    backgroundColor: COLORS.light.primary,
    paddingTop: 64,
    padding: 12,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  headerTitle: { color: "#fff", fontSize: 22, fontWeight: "bold" },
  headerSubtitle: { color: "#7fffd4", fontSize: 14 },
  iconButton: { marginLeft: 12 },
  searchBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 16,
    marginTop: 4,
    marginBottom: 4,
    paddingHorizontal: 12,
    height: 44,
  },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, fontSize: 16, color: "#005f73" },
  scrollArea: { paddingHorizontal: 12, paddingTop: 12, paddingBottom: 20 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.light.ocean,
    marginBottom: 12,
  },
  promoCard: { flex: 1, borderRadius: 12, padding: 12, marginRight: 5 },
  promoTitle: { fontWeight: "bold", fontSize: 14 },
  promoDesc: { fontSize: 10, opacity: 0.9 },
  categoryCard: {
    width: 80,
    height: 80,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    marginRight: 12,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
  },

  categoryIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 6,
  },
  categoryName: {
    fontSize: 13,
    fontWeight: "600",
  },
  productCard: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    alignItems: "center",
    elevation: 2,
  },
  productImage: { fontSize: 36, marginRight: 12 },
  productName: { fontWeight: "bold", color: "#005f73", fontSize: 16 },
  productPrice: { fontWeight: "bold", color: "#005f73", fontSize: 16 },
  productUnit: { fontSize: 12, color: "#0077b6" },
  productVendor: { fontSize: 13, color: "#0077b6", marginBottom: 2 },
  productRating: { fontSize: 13, color: "#333", marginLeft: 4, marginRight: 8 },
  freshnessBadge: {
    backgroundColor: "#7fffd4",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 6,
  },
  freshnessText: { fontSize: 11, color: "#005f73" },
  productLocation: { fontSize: 11, color: "#005f73", marginLeft: 2 },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#cce3de",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  navItem: { alignItems: "center", flex: 1 },
  navLabel: { fontSize: 11, color: "#005f73", marginTop: 2 },
  chatButton: {
    paddingRight: 6,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
  },
});
