import { StyleSheet } from "react-native";
import { COLORS } from "../../constants";
import { Dimensions } from "react-native";

export const buyerDashboardStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.light.background },
  header: {
    backgroundColor: COLORS.light.primary,
    paddingTop: 60,

    padding: 12,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  headerTitle: { color: "#fff", fontSize: 22, fontWeight: "bold" },
  headerSubtitle: { color: "#7fffd4", fontSize: 14 },
  iconButton: { marginLeft: 12 },
  searchBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 16,
    marginTop: 4,
    marginBottom: 4,
    paddingHorizontal: 12,
    height: 44,
  },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, fontSize: 16, color: "#005f73" },
  scrollArea: { paddingHorizontal: 12, paddingTop: 12, paddingBottom: 20 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.light.ocean,
  },
  promoCard: { flex: 1, borderRadius: 12, padding: 12, marginRight: 5 },
  promoTitle: { fontWeight: "bold", fontSize: 14 },
  promoDesc: { fontSize: 10, opacity: 0.9 },
  categoryCard: {
    width: 80,
    height: 40,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    marginRight: 12,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
  },

  categoryIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 6,
  },
  categoryName: {
    fontSize: 13,
    color: COLORS.light.primary,
    fontWeight: "600",
  },
  productImage: {
    width: "100%",
    height: 150,
    borderRadius: 8,
    marginBottom: 8,
  },
  freshnessOverlay: {
    position: "absolute",
    top: 6,
    left: 6,
    backgroundColor: COLORS.light.coral,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
    zIndex: 1,
  },
  freshnessOverlayText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "bold",
  },
  productCard: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 6,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    flexDirection: "column",
  },
  productName: {
    fontWeight: "bold",
    color: COLORS.light.primary,
    fontSize: 16,
    flex: 1,
    marginRight: 8,
  },
  productPrice: {
    fontWeight: "bold",
    color: COLORS.light.coral,
    fontSize: 14,
  },
  productUnit: {
    fontSize: 12,
    color: COLORS.light.oceanMedium,
    marginLeft: 2,
  },
  productVendor: {
    fontSize: 11,
    color: COLORS.light.oceanMedium,
    marginBottom: 2,
    flex: 1, // Add this to allow it to take available space
    marginRight: 8, // Add some spacing between vendor name and rating
  },

  productRating: { fontSize: 11, color: "#333", marginLeft: 4, marginRight: 8 },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#cce3de",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  navItem: { alignItems: "center", flex: 1 },
  navLabel: { fontSize: 11, color: "#005f73", marginTop: 2 },
  chatButton: {
    paddingRight: 10,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  // Add to buyerDashboardStyles
  vendorCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  vendorAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginBottom: 8,
  },
  vendorName: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.light.primary,
    textAlign: "center",
    marginBottom: 4,
  },
  vendorProductCount: {
    fontSize: 12,
    color: "#666",
  },
  unreadBadge: {
    position: "absolute" as "absolute",
    top: -5,
    right: -1,
    backgroundColor: "#ff4444",
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    justifyContent: "center" as "center",
    alignItems: "center" as "center",
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: "#fff",
  },
  unreadBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "bold" as "bold",
  },
});
