import { StyleSheet } from "react-native";
import { COLORS } from "../../constants";

export const cartScreenStyles = StyleSheet.create({
  emptyContainer: { flex: 1, backgroundColor: COLORS.light.background },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.common.white,
    paddingTop: 48,
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#cce3de",
  },
  headerBackBtn: { marginRight: 12, color: COLORS.light.primary },
  headerTitleCart: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.light.primary,
    flex: 1,
  },
  headerItemsCount: { color: COLORS.light.oceanMedium, fontSize: 13 },
  emptyContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.light.primary,
    marginBottom: 6,
  },
  emptyDesc: { color: COLORS.light.oceanMedium, marginBottom: 18 },
  startShoppingBtn: {
    backgroundColor: COLORS.light.primary,
    borderRadius: 16,
    paddingHorizontal: 32,
    paddingVertical: 12,
  },
  startShoppingBtnText: {
    color: COLORS.common.white,
    fontWeight: "bold",
    fontSize: 16,
  },
  cartCard: {
    flexDirection: "row",
    backgroundColor: COLORS.common.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    alignItems: "center",
    elevation: 2,
  },
  cartImage: {
    width: 50,
    height: 50,
    borderRadius: 10,
    marginRight: 12,
  },
  cartName: { fontWeight: "bold", color: COLORS.light.primary, fontSize: 15 },
  cartVendor: { fontSize: 13, color: COLORS.light.oceanMedium },
  cartPrice: { fontSize: 13, color: COLORS.light.primary, marginBottom: 2 },
  trashBtn: {
    backgroundColor: COLORS.common.white,
    borderRadius: 8,
    padding: 4,
  },
  qtyBtn: {
    backgroundColor: COLORS.common.white,
    borderColor: COLORS.light.background,
    borderWidth: 1,
    borderRadius: 8,
    padding: 4,
    marginHorizontal: 2,
  },
  qtyText: {
    width: 24,
    textAlign: "center",
    fontWeight: "bold",
    color: COLORS.light.primary,
    fontSize: 15,
  },
  sectionCard: {
    backgroundColor: COLORS.common.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    elevation: 1,
  },
  sectionTitle: {
    fontWeight: "bold",
    color: COLORS.light.primary,
    fontSize: 15,
    marginBottom: 6,
    marginLeft: 6,
  },
  input: {
    backgroundColor: COLORS.common.gray,
    borderWidth: 1,
    borderColor: COLORS.light.background,
    borderRadius: 10,
    padding: 8,
    fontSize: 15,
    color: COLORS.light.primary,
    marginTop: 2,
  },
  paymentBtn: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.light.background,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    backgroundColor: COLORS.common.gray,
  },
  paymentBtnActive: { borderColor: COLORS.light.primary },
  paymentLabel: {
    fontWeight: "bold",
    color: COLORS.light.primary,
    fontSize: 14,
  },
  paymentDesc: { color: COLORS.light.oceanMedium, fontSize: 12 },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  summaryLabel: { color: COLORS.light.primary, fontSize: 13 },
  summaryValue: { color: COLORS.light.primary, fontSize: 13 },
  summaryDivider: {
    borderBottomWidth: 1,
    borderBottomColor: "#cce3de",
    marginVertical: 6,
  },
  checkoutBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: 12,
  },
  checkoutBtn: {
    backgroundColor: COLORS.light.primary,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: "center",
  },
  checkoutBtnText: {
    color: COLORS.common.white,
    fontWeight: "bold",
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end" as const,
  },
  modalContainer: {
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "85%",
  },
  modalHeader: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold" as const,
    color: COLORS.light.primary,
  },
  closeButton: {
    padding: 4,
  },
  modalContent: {
    padding: 16,
  },
  section: {
    marginBottom: 20,
  },
  sectionHeader: {
    fontSize: 16,
    fontWeight: "600" as const,
    color: COLORS.light.primary,
    marginBottom: 12,
  },
  productCard: {
    flexDirection: "row" as const,
    backgroundColor: "#f8f8f8",
    borderRadius: 12,
    padding: 12,
  },
  productImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
  },
  placeholderImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: "#e0e0e0",
    justifyContent: "center" as const,
    alignItems: "center" as const,
    marginRight: 12,
  },
  productDetails: {
    flex: 1,
    justifyContent: "center" as const,
  },
  productName: {
    fontSize: 16,
    fontWeight: "600" as const,
    marginBottom: 4,
  },
  productVendor: {
    fontSize: 14,
    color: "#666",
    marginBottom: 4,
  },
  productPrice: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: COLORS.light.primary,
  },
  infoRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginBottom: 8,
  },
  infoText: {
    marginLeft: 8,
    fontSize: 14,
    color: "#333",
    flex: 1,
  },
  instructionsText: {
    fontSize: 14,
    color: "#333",
    backgroundColor: "#f8f8f8",
    padding: 12,
    borderRadius: 8,
    lineHeight: 20,
  },
  totalRow: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e0e0e0",
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: "bold" as const,
    color: "#333",
  },
  totalValue: {
    fontSize: 18,
    fontWeight: "bold" as const,
    color: COLORS.light.primary,
  },
  termsContainer: {
    backgroundColor: "#f0f7ff",
    padding: 12,
    borderRadius: 8,
    marginBottom: 24,
  },
  termsText: {
    fontSize: 12,
    color: "#666",
    lineHeight: 16,
    textAlign: "center" as const,
  },
  modalActions: {
    flexDirection: "row" as const,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  editButton: {
    flex: 1,
    backgroundColor: "#f0f0f0",
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center" as const,
    marginRight: 8,
  },
  editButtonText: {
    fontSize: 16,
    fontWeight: "600" as const,
    color: "#666",
  },
  confirmButton: {
    flex: 2,
    backgroundColor: COLORS.light.primary,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center" as const,
    marginLeft: 8,
  },
  confirmButtonText: {
    fontSize: 16,
    fontWeight: "600" as const,
    color: "white",
  },
});
