import { StyleSheet } from "react-native";
import { COLORS } from "../../constants";

export const cartScreenStyles = StyleSheet.create({
  emptyContainer: { flex: 1, backgroundColor: COLORS.light.background },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.common.white,
    paddingTop: 48,
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#cce3de",
  },
  headerBackBtn: { marginRight: 12, color: COLORS.light.primary },
  headerTitleCart: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.light.primary,
    flex: 1,
  },
  headerItemsCount: { color: COLORS.light.oceanMedium, fontSize: 13 },
  emptyContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.light.primary,
    marginBottom: 6,
  },
  emptyDesc: { color: COLORS.light.oceanMedium, marginBottom: 18 },
  startShoppingBtn: {
    backgroundColor: COLORS.light.primary,
    borderRadius: 16,
    paddingHorizontal: 32,
    paddingVertical: 12,
  },
  startShoppingBtnText: {
    color: COLORS.common.white,
    fontWeight: "bold",
    fontSize: 16,
  },
  cartCard: {
    flexDirection: "row",
    backgroundColor: COLORS.common.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    alignItems: "center",
    elevation: 2,
  },
  cartImage: {
    width: 50,
    height: 50,
    borderRadius: 10,
    marginRight: 12,
  },
  cartName: { fontWeight: "bold", color: COLORS.light.primary, fontSize: 15 },
  cartVendor: { fontSize: 13, color: COLORS.light.oceanMedium },
  cartPrice: { fontSize: 13, color: COLORS.light.primary, marginBottom: 2 },
  trashBtn: {
    backgroundColor: COLORS.common.white,
    borderRadius: 8,
    padding: 4,
  },
  qtyBtn: {
    backgroundColor: COLORS.common.white,
    borderColor: COLORS.light.background,
    borderWidth: 1,
    borderRadius: 8,
    padding: 4,
    marginHorizontal: 2,
  },
  qtyText: {
    width: 24,
    textAlign: "center",
    fontWeight: "bold",
    color: COLORS.light.primary,
    fontSize: 15,
  },
  sectionCard: {
    backgroundColor: COLORS.common.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    elevation: 1,
  },
  sectionTitle: {
    fontWeight: "bold",
    color: COLORS.light.primary,
    fontSize: 15,
    marginBottom: 6,
    marginLeft: 6,
  },
  input: {
    backgroundColor: COLORS.common.gray,
    borderWidth: 1,
    borderColor: COLORS.light.background,
    borderRadius: 10,
    padding: 8,
    fontSize: 15,
    color: COLORS.light.primary,
    marginTop: 2,
  },
  paymentBtn: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.light.background,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    backgroundColor: COLORS.common.gray,
  },
  paymentBtnActive: { borderColor: COLORS.light.primary },
  paymentLabel: {
    fontWeight: "bold",
    color: COLORS.light.primary,
    fontSize: 14,
  },
  paymentDesc: { color: COLORS.light.oceanMedium, fontSize: 12 },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  summaryLabel: { color: COLORS.light.primary, fontSize: 13 },
  summaryValue: { color: COLORS.light.primary, fontSize: 13 },
  summaryDivider: {
    borderBottomWidth: 1,
    borderBottomColor: "#cce3de",
    marginVertical: 6,
  },
  checkoutBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: 12,
  },
  checkoutBtn: {
    backgroundColor: COLORS.light.primary,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: "center",
  },
  checkoutBtnText: {
    color: COLORS.common.white,
    fontWeight: "bold",
    fontSize: 16,
  },
});
